// generateAuraReport.ts — builds the migraine-aura PDF report (jsPDF + Roboto).
// Ported 1:1 from the Hugo static/js/generateAuraReport.js; browser-only
// (uses the DOM to parse the narrative HTML and load the logo). Typed, with
// jsPDF imported as a module rather than read off window.

import jsPDF from "jspdf";
import { generateNarrativeSummary } from "../engine/narrative";
import { t } from "../engine/i18n";
import { registerRoboto } from "./roboto";
import type {
  AcuteChronicAnswers,
  AcuteChronicData,
  AuraCharacteristicsAnswers,
  CriterionBAnswers,
  Lang,
  UserInfo,
} from "../engine/types";

const FONT = "Roboto";

export interface ReportCharacteristics {
  progression?: boolean;
  succession?: boolean;
  duration?: boolean;
  laterality?: boolean;
  positive?: boolean;
  headacheOnset?: boolean;
}

/** The PDF input: the modality answers plus the rest of the collected state. */
export interface ReportData {
  criterionB: CriterionBAnswers;
  userInfo: UserInfo;
  acuteChronicData: AcuteChronicData;
  acuteChronicAnswers: AcuteChronicAnswers;
  auraCharacteristicsAnswers: AuraCharacteristicsAnswers;
  modalities?: string[];
  characteristics?: ReportCharacteristics;
  otherDescription?: string;
  lang?: Lang;
}

export type FlowType = "standard" | "plus-other" | "other-only" | string;

// --- Image Loader ---
async function loadImageAsBase64(url: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => {
      const c = document.createElement("canvas");
      c.width = img.width;
      c.height = img.height;
      c.getContext("2d")!.drawImage(img, 0, 0);
      resolve(c.toDataURL("image/png"));
    };
    img.onerror = reject;
    img.src = url;
  });
}

// --- Shared Components ---
async function drawHeader(doc: jsPDF, title?: string): Promise<void> {
  const headerTitle = title || t("flow.report.title", "Migraine Aura Report");
  doc.setFontSize(14).setFont(FONT, "normal").text(headerTitle, 20, 20);

  try {
    const url = "/images/report-logo.png";
    const base64 = await loadImageAsBase64(url);
    const img = new Image();
    img.src = url;
    await new Promise((res, rej) => {
      img.onload = res;
      img.onerror = rej;
    });
    const h = 40 / (img.width / img.height);
    doc.addImage(base64, "PNG", 150, 10, 40, h);
  } catch (e) {
    console.warn("Logo missing:", e);
  }

  doc.setFontSize(9).setFont(FONT, "normal");
  doc.setTextColor(0);
  const disclaimerLead = t(
    "flow.report.headerDisclaimer.lead",
    "This automated report adheres to ICHD-3 criteria and is",
  );
  const disclaimerEmph = t("flow.report.headerDisclaimer.emph", " not a substitute ");
  const disclaimerTail = t(
    "flow.report.headerDisclaimer.tail",
    "for professional medical diagnosis.",
  );
  doc.text(disclaimerLead, 20, 26);
  doc.setTextColor(200, 0, 0);
  doc.text(disclaimerEmph, doc.getTextWidth(disclaimerLead) + 20, 26);
  doc.setTextColor(0);
  doc.text(disclaimerTail, doc.getTextWidth(disclaimerLead + disclaimerEmph) + 20, 26);

  doc.setFontSize(10).setTextColor(0, 0, 0);
  doc.setDrawColor(0);
  doc.line(20, 28, 190, 28);
}

function drawFooter(doc: jsPDF): void {
  const h = doc.internal.pageSize.getHeight();
  doc.setFontSize(8).setTextColor(120).setFont(FONT, "normal");
  doc.text(
    t("flow.report.footer.generatedBy", "Generated by Migraine Aura Foundation"),
    20,
    h - 10,
  );
  doc.text(
    t("flow.report.footer.url", "www.migraine-aura-foundation.org"),
    150,
    h - 10,
    { align: "right" },
  );
  doc.setFontSize(7).setTextColor(150);
  doc.text(
    t(
      "flow.report.footer.disclaimerNote",
      "This assessment is not a diagnosis. See full disclaimer on last page.",
    ),
    20,
    h - 5,
  );
}

function drawSelectedModalities(doc: jsPDF, modalities: string[] = [], y = 35): number {
  const labels: Record<string, string> = {
    visual: t("flow.report.modality.visual", "Visual"),
    sensory: t("flow.report.modality.sensory", "Sensory"),
    speech: t("flow.report.modality.speech", "Speech"),
    motor: t("flow.report.modality.motor", "Motor"),
    brainstem: t("flow.report.modality.brainstem", "Brainstem"),
    retinal: t("flow.report.modality.retinal", "Retinal"),
    other: t("flow.report.modality.other", "Other"),
  };

  doc.setFont(FONT, "normal").setFontSize(11);
  doc.text(t("flow.report.section.selectedModalities", "Selected Aura Modalities"), 20, y);
  y += 8;

  doc.setFont(FONT, "normal").setFontSize(10);
  const lineHeight = doc.getFontSize() * doc.getLineHeightFactor();

  modalities.forEach((m) => {
    doc.text(`• ${labels[m] || m}`, 25, y);
    y += lineHeight;
  });

  return y;
}

function buildOtherOnlyContent(doc: jsPDF, data: ReportData, y: number): void {
  const text =
    data.otherDescription ||
    t("flow.report.otherDescription.empty", "[No description provided]");
  doc
    .setFont(FONT, "normal")
    .setFontSize(11)
    .text(t("flow.report.section.otherDescribed", "Described 'Other' Aura Symptom:"), 20, y);
  doc.setFont(FONT, "normal").setFontSize(10);
  const lines = doc.splitTextToSize(text, 170);
  doc.text(lines, 25, y + 10);
}

function buildStandardAuraContent(doc: jsPDF, data: ReportData, y: number): void {
  const c = data.characteristics ?? {};
  const fields = [
    { label: t("flow.report.characteristic.progression.label", "Progression"), text: t("flow.report.characteristic.progression.text", "Spreads gradually over minutes"), v: c.progression },
    { label: t("flow.report.characteristic.succession.label", "Succession"), text: t("flow.report.characteristic.succession.text", "2+ symptoms in succession"), v: c.succession },
    { label: t("flow.report.characteristic.duration.label", "Duration"), text: t("flow.report.characteristic.duration.text", "Each lasts 5–60 minutes"), v: c.duration },
    { label: t("flow.report.characteristic.laterality.label", "Laterality"), text: t("flow.report.characteristic.laterality.text", "At least one unilateral"), v: c.laterality },
    { label: t("flow.report.characteristic.positive.label", "Positive/Negative"), text: t("flow.report.characteristic.positive.text", "At least one positive symptom"), v: c.positive },
    { label: t("flow.report.characteristic.headache.label", "Headache"), text: t("flow.report.characteristic.headache.text", "Followed by headache <60 min"), v: c.headacheOnset },
  ];

  doc
    .setFont(FONT, "normal")
    .setFontSize(12)
    .text(t("flow.report.section.auraCharacteristics", "Aura Characteristics"), 20, y);
  y += 8;

  const yesLabel = t("flow.report.verdict.yes", "Yes");
  const noLabel = t("flow.report.verdict.no", "No");

  fields.forEach((f) => {
    const yes = f.v === true;
    const [r, g, b] = yes ? [0, 150, 0] : [200, 0, 0];
    doc.setFont(FONT, "normal").setFontSize(10).setTextColor(0);
    doc.text(`${f.label}:`, 20, y);
    doc.setFont(FONT, "normal").setTextColor(r, g, b).text(yes ? yesLabel : noLabel, 55, y);
    doc.setFontSize(9).setTextColor(0);
    const lines = doc.splitTextToSize(f.text, 170);
    doc.text(lines, 25, y + 5);
    y += 12 + (lines.length - 1) * 5;
  });

  const passed = fields.filter((f) => f.v).length;
  const summary = t(
    "flow.report.characteristicsCount",
    "You meet {passed} of 6 clinical characteristics for migraine aura (C criterion).",
    { passed },
  );
  doc
    .setFont(FONT, "normal")
    .setFontSize(11)
    .setTextColor(passed >= 3 ? 0x009600 : 0xcc0000);
  doc.text(doc.splitTextToSize(summary, 170), 20, (y += 5));
  doc.setTextColor(0);
}

async function drawNarrativeSummary(doc: jsPDF, htmlString: string, startY = 35): Promise<number> {
  const tempDiv = document.createElement("div");
  tempDiv.innerHTML = htmlString;
  document.body.appendChild(tempDiv);

  let y = startY;
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const lineHeight = 6;

  const addLines = async (lines: string[]) => {
    doc.setFont(FONT, "normal").setFontSize(10);
    for (const line of lines) {
      if (y + lineHeight > pageHeight - margin) {
        drawFooter(doc);
        doc.addPage();
        await drawHeader(doc);
        y = 30;
      }
      doc.text(line, margin, y);
      y += lineHeight;
    }
  };

  for (const node of Array.from(tempDiv.childNodes)) {
    if (node.nodeType === Node.ELEMENT_NODE) {
      const el = node as HTMLElement;
      if (el.tagName === "H3" || el.tagName === "H2" || el.tagName === "H4") {
        const text = el.innerText.trim();
        if (text) {
          doc.setFont(FONT, "normal").setFontSize(12);
          if (y + lineHeight > pageHeight - margin) {
            drawFooter(doc);
            doc.addPage();
            await drawHeader(doc);
            y = 30;
          }
          doc.text(text, margin, y);
          y += lineHeight;
        }
      } else if (el.tagName === "P") {
        const lines = doc.splitTextToSize(el.innerText.trim(), 170);
        await addLines(lines);
        y += lineHeight / 2;
      } else if (el.tagName === "UL") {
        for (const li of Array.from(el.querySelectorAll("li"))) {
          const lines = doc.splitTextToSize(`• ${(li as HTMLElement).innerText.trim()}`, 170);
          await addLines(lines);
        }
        y += lineHeight / 2;
      }
    }
  }

  drawFooter(doc);
  document.body.removeChild(tempDiv);
  return y;
}

async function appendDisclaimerPage(doc: jsPDF): Promise<void> {
  doc.addPage();
  await drawHeader(doc);
  drawFooter(doc);
  doc
    .setFont(FONT, "normal")
    .setFontSize(12)
    .text(t("flow.report.disclaimer.heading", "⚠️ Disclaimer"), 20, 30);
  doc.setFont(FONT, "normal").setFontSize(10);
  const disclaimer = t(
    "flow.report.disclaimer.body",
    "This assessment was conducted using a self-report tool developed by the Migraine Aura Foundation. It is not a medical diagnosis.\n\nNeurological symptoms can have many causes. This assumes your symptoms are not better explained by another medical condition such as epilepsy, stroke, multiple sclerosis, or eye disorders.\n\nIf your symptoms are new, worsening, or unusual, seek medical advice immediately.",
  );
  doc.text(doc.splitTextToSize(disclaimer, 170), 20, 45);
}

// --- Main entry ---
export async function generateAuraReport(flowType: FlowType, data: ReportData): Promise<void> {
  const doc = new jsPDF();
  await registerRoboto(doc);
  doc.setFont(FONT, "normal");

  await drawHeader(doc);
  let y = 30;

  const narrativeHtml = generateNarrativeSummary({
    data: data.criterionB,
    userInfo: data.userInfo,
    acuteChronicData: data.acuteChronicData,
    acuteChronicAnswers: data.acuteChronicAnswers,
    auraCharacteristicsAnswers: data.auraCharacteristicsAnswers,
    lang: data.lang,
  });

  y += 10;
  y = await drawNarrativeSummary(doc, narrativeHtml, y);

  doc.addPage();
  await drawHeader(doc);
  y = 30;

  y = drawSelectedModalities(doc, data.modalities || [], y + 5);

  if ((data.modalities || []).includes("other")) {
    buildOtherOnlyContent(doc, data, y);
    y += 20;
  }

  if (flowType === "standard") {
    buildStandardAuraContent(doc, data, y);
  } else if (flowType === "plus-other" || flowType === "other-only") {
    buildOtherOnlyContent(doc, data, y);
  } else {
    doc
      .setFont(FONT, "normal")
      .setFontSize(10)
      .text(t("flow.report.unknownFlowType", "Unknown flow type."), 20, y);
  }

  drawFooter(doc);
  await appendDisclaimerPage(doc);
  doc.save(t("flow.report.fileName", "aura_report.pdf"));
}
